# default values
all:
  homepage_url: http://www.googlevolume.com
  web:
    images: /var/www/www.googlevolume.com/web/images
    charts_dir: charts
  isicsSitemapXML:
    modules:  [report]
  recaptcha:
    publickey: 6LeefAQAAAAAAFQE45ZyTerF6Op-ZxO7vh6dLdfu
    privatekey: 6LeefAQAAAAAAMoGfya5J6YVBIeGqpsCBumPrsun