# default rules
snippet:
  url:   /:id
  param: { module: report, action: show }

homepage:
  url:   /
  param: { module: report, action: showByDate, order: desc }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
  
isics_sitemap_xml:
  url:   /sitemap.xml
  param: { module: isicsSitemapXML, action: index }

chart_image:
  url:   /report/:id.png
  param: { module: report, action: showImage } 