# default rules
homepage:
  url:   /
  param: { module: report, action: showByDate, order: desc }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
