default:
  http_metas:
    content-type: text/html

  metas:
    title:        Google Volume
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    [main]

  javascripts:    [jquery-1.3.2.min.js]

  has_layout:     on
  layout:         layout

all:
  javascripts: []