default:
  http_metas:
    content-type: text/html

  metas:
    title:        Google Volume
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    [main]

  javascripts:    []

  has_layout:     on
  layout:         layout

all:
  javascripts: [%SF_PROTOTYPE_WEB_DIR%/js/prototype]