propel:
  sf_guard_user_profile:
    _attributes:      { phpName: sfGuardUserProfile }
    id:               ~
    user_id:          { type: integer, required: true, foreignTable: sf_guard_user, foreignReference: id, onDelete: cascade }
    email:            { type: varchar, size: 255, required: true }
    first_name:       { type: varchar, size: 255, required: true }
    last_name:        { type: varchar, size: 255, required: true }
    activation_key:   { type: varchar, size: 32 }
    gender:           { type: char, size: 1, required: false }
    webpage:          { type: varchar, size: 255, required: false }
    birthday:         { type: date, required: false }

  projecty_query:
    _attributes:        { phpName: Query }
    id:                 ~
    query:              { type: varchar, size: 255, required: true }
    standard_deviation: { type: double, required: true, default: 0 }
    managed:            { type: boolean, required: true, default: false }
    created_at:         ~

  projecty_report:
    _attributes:      { phpName: Report }
    id:               ~
    user_id:          { type: integer, foreignTable: sf_guard_user, foreignReference: id, onDelete: cascade }
    title:            { type: varchar, size: 255, required: true }
    stripped_title:   { type: varchar, size: 255 }
    description:      { type: varchar, size: 255, required: false }
    public_record:    { type: boolean, required: true, default: true }
    view_count:       { type: integer, required: true, default: 0 }
    mail_frequency:   { type: char, required: true, default: 'N' }
    created_at:       ~
    updated_at:       ~

  projecty_report_query:
    _attributes:      { phpName: ReportQuery }
    query_id:         { type: integer, required: true, primaryKey: true, foreignTable: projecty_query, foreignReference: id }
    report_id:        { type: integer, required: true, primaryKey: true, foreignTable: projecty_report, foreignReference: id, onDelete: cascade }
    title:            { type: varchar, size: 255, required: false }
    created_at:       ~

  projecty_query_result_daily:
    _attributes:      { phpName: QueryResult }
    id:               ~
    query_id:         { type: integer, required: true, primaryKey: true, foreignTable: projecty_query, foreignReference: id, onDelete: cascade }
    result_size:      { type: bigint, required: true }
    result_date:      { type: date, required: true }
    result_count:     { type: integer, required: true, default: 1 }
    created_at:       ~
    updated_at:       ~

  projecty_query_result:
    _attributes:      { phpName: QueryResultBulk }
    id:               ~
    query_id:         { type: integer, required: true, primaryKey: true, foreignTable: projecty_query, foreignReference: id, onDelete: cascade }
    result_size:      { type: bigint, required: true }
    created_at:       ~

  projecty_report_tag:
    _attributes:      { phpName: ReportTag }
    report_id:        { type: integer, required: true, primaryKey: true, foreignTable: projecty_report, foreignReference: id, onDelete: cascade }
    name:             { type: varchar, size: 100, required: true, primaryKey: true }
    created_at:       ~