generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Query
    theme:            default

    fields:
      query:                { name: Query Text}
      managed:              { name: Managed }
      created_at:           { name: Create Date }

    list:
      title:                query list
      display:              [id, managed, _google, _num_of_results, _num_of_reports, created_at]
      fields:
        created_at:         { params: date_format='dd/MM/yyyy' }
      sort: id      
      filters:              [id, managed, query]
      
    edit:
      title:                query add & edit
      display:
        "Editable":         [query, managed]
        "Informative":      [created_at]
      fields:
        created_at:         {type: plain}